# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JourneyPlan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JourneyPlan
  pod 'EMTNeumorphicView'
  pod 'SnapKit'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Kingfisher'

  target 'JourneyPlanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JourneyPlanUITests' do
    # Pods for testing
  end

end
